server: #디폴트 8080
  port: 8080 
#  servlet:
#    context-path: /myspring # 디폴트 "/"

#타임리프 템플릿 엔진 설정(디폴트)
spring:
  thymeleaf:
    prefix: classpath:/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: false # set to false for hot refresh 서버 재시작하지 않아도 html변경 사항이 적용됨(새로고침)
#messages.properties파일 위치 설정.기본값은 messages
  messages:
    basename: i18n/messages #src/main/resources 밑에 i18n폴더 생성후 messages.properties저장
#정적자원의 디폴트 설정
  mvc:
    static-path-pattern: /** 
  web:
    resources:      
      static-location: classpath:/static/ #정적자원의 물리적 위치
      add-mappings: true #자동 매핑 활성화(true:기본값),비 활성화시(false) path-pattern 및 static-location등이 적용되지 않는다